info:
  component: ${spring.application.name}

this:
  is:
    some:
      common:
        prop: widoczne wszędzie ! dla każdej aplikacji, niezależnie od nazwy !

---

graphite:
  host: localhost
  port: 2003

---

spring:
  zipkin:
    baseUrl: http://localhost:8070/
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true