info:
  component: ${spring.application.name}

this:
  is:
    some:
      common:
        prop: widoczne wszędzie ! dla każdej aplikacji, niezależnie od nazwy !

graphite:
  host: localhost
  port: 2003
