server:
  port: 0

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/${info.instanceId};AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE

management:
  shell:
    auth:
      simple:
        user:
          name: user
          password: pass

my:
  refreshable:
    message: Initial value of message. Change 4
